import { describe, expect, it } from "vitest";
import { initialTemplateModel } from "../templateData";
import { findNodeById } from "../treeUtils";
import { parseMarkupToAst, parseStyleString, reconcileMarkupToCommand, templateToMarkup, validateMarkupSyntax } from "../codeReconciler";

const model=structuredClone(initialTemplateModel);
describe("Phase 2 code reconciler",()=>{
  it("serializes selected node using base properties",()=>{const n=findNodeById(model.elements,"hero-heading")!;const m=templateToMarkup(n,"selected");expect(m).toContain('id="hero-heading"');expect(m).toContain('font-size: 56px');expect(m).not.toContain('34px');});
  it("serializes the full nested document",()=>{const m=templateToMarkup(model,"full");expect(m.startsWith(`<main id="${model.templateId}">`)).toBe(true);expect(m).toContain("<section id=\"hero\"");});
  it("parses nested tags and attributes",()=>{const r=parseMarkupToAst(`<section id="hero"><div id="content"><h1 id="heading" style="font-size: 48px">Hello</h1></div></section>`);expect(r.success).toBe(true);if(r.success)expect(r.root.children[0].children[0].children[0].id).toBe("heading");});
  it("rejects unclosed, mismatched, missing-ID, duplicate-ID and dynamic expressions",()=>{expect(validateMarkupSyntax(`<section id="hero"><h1 id="x"></section>`).valid).toBe(false);expect(validateMarkupSyntax(`<section><h1 id="x">x</h1></section>`).valid).toBe(false);expect(validateMarkupSyntax(`<section id="hero">{items.map(x => x)}</section>`).valid).toBe(false);const dup=reconcileMarkupToCommand(model,`<h1 id="hero-heading">a</h1><p id="hero-heading">b</p>`,model.revision,"full");expect(dup.success).toBe(false);});
  it("parses and range-validates CSS",()=>{expect(parseStyleString("font-size: 48px; color: #18181B").valid).toBe(true);expect(parseStyleString("z-index: 4").valid).toBe(false);expect(parseStyleString("font-size: banana").valid).toBe(false);expect(parseStyleString("font-size: 9999px").valid).toBe(false);});
  it("reconciles selected content safely including empty content",()=>{const n=findNodeById(model.elements,"hero-heading")!;const original=templateToMarkup(n,"selected");const changed=original.replace(n.content!,"");const r=reconcileMarkupToCommand(model,changed,model.revision,"selected","hero-heading");expect(r.success).toBe(true);if(r.success)expect(r.command.changes.patches?.["hero-heading"]?.content).toBe("");});
  it("rejects selected-scope edits outside selected subtree",()=>{const other=templateToMarkup(findNodeById(model.elements,"services")!,"selected");const r=reconcileMarkupToCommand(model,other,model.revision,"selected","hero-heading");expect(r.success).toBe(false);});
  it("rejects deleted canonical IDs in full template mode",()=>{const m=templateToMarkup(model,"full").replace(/<p id="hero-desc"[^>]*>.*?<\/p>/s,"");const r=reconcileMarkupToCommand(model,m,model.revision,"full");expect(r.success).toBe(false);});
  it("supports multi-element independent changes",()=>{const full=templateToMarkup(model,"full").replace("Designing digital experiences that move businesses forward.","New headline").replace("We partner with ambitious teams to design, build, and ship products that feel effortless to use.","New paragraph");const r=reconcileMarkupToCommand(model,full,model.revision,"full");expect(r.success).toBe(true);if(r.success){expect(Object.keys(r.command.changes.patches??{})).toEqual(expect.arrayContaining(["hero-heading","hero-desc"]));expect(r.command.changes.patches?.["hero-heading"]?.content).toBe("New headline");expect(r.command.changes.patches?.["hero-desc"]?.content).toBe("New paragraph");}});
});
