import React, { useMemo, useState } from "react";
import type { EditCommand, ElementNode, RevisionEntry, TemplateModel } from "../lib/types";
import { createForwardRestoreCommand, filterHistoryEntries } from "../lib/historyManager";
import { IconClose, IconHistory, IconRotateCcw } from "./icons";

interface Props { model: TemplateModel; history: RevisionEntry[]; selectedNode: ElementNode | null; isOpen: boolean; onClose: () => void; onCommitCommand: (command: EditCommand) => { success: boolean; error?: { message: string } }; }
export const HistoryDrawer: React.FC<Props> = ({ model, history, selectedNode, isOpen, onClose, onCommitCommand }) => {
  const [kind, setKind] = useState<"all" | "ai" | "manual">("all"); const [selectedOnly, setSelectedOnly] = useState(false); const [scope, setScope] = useState<"all" | "desktop" | "tablet" | "mobile">("all");
  const entries = useMemo(() => filterHistoryEntries([...history].reverse(), { kind, selectedElementId: selectedOnly ? selectedNode?.id : undefined, scope }), [history, kind, selectedOnly, selectedNode, scope]);
  if (!isOpen) return null;
  return <aside className="fixed inset-y-0 right-0 z-50 w-[380px] bg-[#fbfbfa] border-l border-zinc-200 text-zinc-900 shadow-2xl flex flex-col">
    <div className="px-4 h-12 border-b border-zinc-200 flex items-center justify-between"><div className="flex items-center gap-2"><IconHistory size={16}/><div><div className="text-xs font-semibold tracking-[0.12em] uppercase">Audit History</div><div className="text-[10px] text-zinc-400">{history.length} revisions</div></div></div><button type="button" onClick={onClose} className="p-1.5 rounded hover:bg-zinc-100"><IconClose size={15}/></button></div>
    <div className="p-3 border-b border-zinc-200 flex flex-wrap gap-1.5"><button className={`px-2 py-1 rounded text-[10px] border ${kind === "all" && !selectedOnly ? "bg-zinc-900 text-white border-zinc-900" : "border-zinc-200"}`} onClick={() => {setKind("all");setSelectedOnly(false)}}>All</button>{selectedNode && <button className={`px-2 py-1 rounded text-[10px] border ${selectedOnly ? "bg-zinc-900 text-white border-zinc-900" : "border-zinc-200"}`} onClick={() => setSelectedOnly((v) => !v)}>Selected</button>}<button className={`px-2 py-1 rounded text-[10px] border ${kind === "ai" ? "bg-zinc-900 text-white border-zinc-900" : "border-zinc-200"}`} onClick={() => {setKind("ai");setSelectedOnly(false)}}>AI</button><button className={`px-2 py-1 rounded text-[10px] border ${kind === "manual" ? "bg-zinc-900 text-white border-zinc-900" : "border-zinc-200"}`} onClick={() => {setKind("manual");setSelectedOnly(false)}}>Manual</button><select value={scope} onChange={(e) => setScope(e.target.value as typeof scope)} className="ml-auto text-[10px] bg-transparent border border-zinc-200 rounded px-2 py-1"><option value="all">All scopes</option><option value="desktop">Desktop</option><option value="tablet">Tablet</option><option value="mobile">Mobile</option></select></div>
    <div className="flex-1 overflow-auto p-3 space-y-2">{entries.length === 0 ? <div className="h-40 flex items-center justify-center text-xs text-zinc-400">No matching revisions.</div> : entries.map((entry) => <div key={entry.revisionId} className="bg-white border border-zinc-200 rounded-lg p-3"><div className="flex items-center justify-between text-[10px] text-zinc-400"><span>{entry.displayTime}</span><span>{entry.source}</span></div><div className="mt-1 text-xs font-semibold">{entry.elementName}</div><div className="text-[10px] font-mono text-zinc-400 mt-0.5">{entry.elementId} · {entry.scope}</div>{entry.propertyKey === "structure" && entry.structure ? <div className="mt-2 text-[11px] text-zinc-600">Order {entry.structure.beforeIndex + 1} → {entry.structure.afterIndex + 1}</div> : entry.beforeState.content !== undefined ? <div className="mt-2 text-[11px]"><div className="line-through text-zinc-400">{entry.beforeState.content}</div><div className="text-zinc-800">{entry.afterState.content}</div></div> : <div className="mt-2 text-[10px] font-mono text-zinc-500">{Object.keys(entry.afterState.props ?? {}).map((k) => `${k}: ${String(entry.afterState.props?.[k as keyof typeof entry.afterState.props])}`).join(" · ")}</div>}<div className="mt-2 flex justify-end"><button type="button" onClick={() => { try { const cmd = createForwardRestoreCommand(entry, model); onCommitCommand(cmd); } catch { /* invalid historical entry is simply not restorable */ } }} className="inline-flex items-center gap-1.5 px-2 py-1 rounded border border-zinc-200 text-[10px] hover:bg-zinc-50"><IconRotateCcw size={11}/>Restore</button></div></div>)}</div>
  </aside>;
};
