import React from "react";
import type { Proposal, ProposalDiff } from "../lib/types";

interface Props { proposal: Proposal; stale: boolean; acceptedIds: string[]; rejectedIds: string[]; onSetDecision: (id: string, decision: "accepted" | "rejected") => void; onApply: () => void; onDismiss: () => void; }
export const ProposalCard: React.FC<Props> = ({ proposal, stale, acceptedIds, rejectedIds, onSetDecision, onApply, onDismiss }) => <section className="border border-zinc-200 bg-white shadow-sm rounded-xl overflow-hidden" aria-label="Edit proposal">
  <div className="px-4 py-3 border-b border-zinc-200 flex items-start justify-between gap-4"><div><div className="text-[11px] uppercase tracking-[0.14em] font-semibold text-zinc-500">Edit proposal</div><div className="text-sm font-medium text-zinc-900 mt-1">{proposal.description}</div></div><span className="text-[10px] text-zinc-500 border border-zinc-200 rounded px-2 py-1">{proposal.scope}</span></div>
  {stale && <div className="px-4 py-2 bg-amber-50 border-b border-amber-200 text-[11px] text-amber-800">This proposal is stale because the document changed after it was generated.</div>}
  <div className="max-h-[360px] overflow-auto divide-y divide-zinc-100">
    {proposal.diffs.map((diff: ProposalDiff) => { const decision = acceptedIds.includes(diff.elementId) ? "accepted" : rejectedIds.includes(diff.elementId) ? "rejected" : "pending"; return <div key={diff.elementId} className={`p-4 ${decision === "rejected" ? "opacity-50" : ""}`}>
      <div className="flex items-center justify-between gap-3"><div><div className="text-sm font-medium text-zinc-900">{diff.elementName}</div><div className="text-[10px] text-zinc-500 font-mono">{diff.elementId}</div></div><div className="text-[10px] uppercase tracking-wide text-zinc-400">{decision}</div></div>
      <div className="grid grid-cols-2 gap-3 mt-3"><div className="rounded-lg border border-zinc-200 bg-zinc-50 p-3"><div className="text-[10px] uppercase tracking-wide text-zinc-400">Before</div><pre className="mt-2 text-[11px] text-zinc-600 whitespace-pre-wrap break-words font-sans">{diff.beforeContent ?? JSON.stringify(diff.beforeProps ?? {}, null, 2)}</pre></div><div className="rounded-lg border border-zinc-200 bg-[#f6f7f4] p-3"><div className="text-[10px] uppercase tracking-wide text-zinc-400">After</div><pre className="mt-2 text-[11px] text-zinc-800 whitespace-pre-wrap break-words font-sans">{diff.afterContent ?? JSON.stringify(diff.afterProps ?? {}, null, 2)}</pre></div></div>
      <div className="mt-3 flex gap-2"><button type="button" onClick={() => onSetDecision(diff.elementId, "accepted")} disabled={stale} className={`px-2.5 py-1 rounded-md text-[11px] border ${decision === "accepted" ? "bg-zinc-900 text-white border-zinc-900" : "border-zinc-200 text-zinc-600 hover:bg-zinc-50"}`}>Accept</button><button type="button" onClick={() => onSetDecision(diff.elementId, "rejected")} className={`px-2.5 py-1 rounded-md text-[11px] border ${decision === "rejected" ? "bg-zinc-200 text-zinc-700 border-zinc-300" : "border-zinc-200 text-zinc-600 hover:bg-zinc-50"}`}>Reject</button></div>
    </div>; })}
  </div>
  <div className="px-4 py-3 border-t border-zinc-200 flex items-center justify-end gap-2"><button type="button" onClick={onDismiss} className="px-3 py-1.5 rounded-md text-xs text-zinc-600 hover:bg-zinc-100">Dismiss</button><button type="button" disabled={stale || acceptedIds.length === 0} onClick={onApply} className="px-3.5 py-1.5 rounded-md bg-zinc-900 text-white text-xs font-medium disabled:opacity-30">Apply accepted</button></div>
</section>;
